version: "3.8"
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    volumes:
      - "static_files:/home/src/config/staticfiles"
    depends_on:
      - web
  web:
    build: .
    container_name: "web_cont"
    command: >
      bash -c "/scripts/wait-for-it.sh db:5432    
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn config.wsgi:application --bind 0.0.0.0:8030 --log-level=debug"
    environment:
      - COUNTRY_PREFIX=CL
      - DJANGO_SECRET_KEY=*0n3o(6y8t_k1iw_%7^x)riptvn-%kde*%h8e34d%9tpt466ll
      - POSTGRES_HOST=db
      - POSTGRES_DB=citdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7F6tfFDqxc4nEDSc
      - POSTGRES_PORT=5432
      - DJANGO_DEBUG=False
      - DJANGO_SETTINGS_MODULE=config.settings.base
      - ENVIRONMENT=DEV
      - LOGS_DIR=logs
    expose:
      - 8030
    volumes: 
        - "./src:/src"
        - "static_files:/src/config/staticfiles"
    depends_on:
      - db
  db:
    image: postgres
    container_name: "db_cont"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=citdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7F6tfFDqxc4nEDSc
  pgadmin:
    container_name: "pgadmin_cont"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "8080:80"
    depends_on:
      - db
  
volumes:
  static_files: